### ISSUE TITLE
rejoin-portal loop bug

### ISSUE THREAD

**Issue by MasterLuke117** [PetteriM1/Portals#1]
if save player data is enabled in nukkit.yml,  when you return to the world you used the portal in you cannot rejoin as it places you back in the portal again on rejoin then instantly puts you back in the world you were sent to with the portal.   

with save player data off, you can join back as it will put you back at spawn

so, simply when you use the portal and leave the world that the portal is in, your rejoin spot will be back into that portal again.

**Comment by PetteriM1** [comment]
Maybe I could add option to set player spawnpoint to default when he enters to portal

**Comment by MasterLuke117** [comment]
Fixed!  thank you!
